import type { DashboardSnapshot } from "./telemetry.ts";

export const demoSnapshot: DashboardSnapshot = {
  mode: "demo",
  capturedAt: "2026-07-11T05:00:00.000Z",
  agents: [
    {
      id: "agent-claude-root",
      parentId: null,
      name: "Release coordinator",
      provider: "claude",
      model: "claude-sonnet",
      effort: "high",
      status: "running",
      task: "Coordinate the monitoring portal delivery",
      spawnMethod: "root",
      cwd: "~/projects/monitor-agents",
      startedAt: "2026-07-11T01:00:00.000Z",
      endedAt: null,
      lastActivityAt: "2026-07-11T04:58:00.000Z",
      tokenUsage: {
        input: 18_000,
        output: 4_600,
        cached: 7_200,
        contextUsed: 46_800,
        contextLimit: 200_000,
      },
      costUsd: 0.21,
      toolCalls: 8,
    },
    {
      id: "agent-codex-api",
      parentId: "agent-claude-root",
      name: "API investigator",
      provider: "codex",
      model: "codex-1",
      effort: "medium",
      status: "completed",
      task: "Define the telemetry ingestion contract",
      spawnMethod: "bash",
      spawnCommand: "codex exec --json \"define telemetry contract\"",
      cwd: "~/projects/monitor-agents",
      startedAt: "2026-07-11T01:10:00.000Z",
      endedAt: "2026-07-11T02:20:00.000Z",
      lastActivityAt: "2026-07-11T02:20:00.000Z",
      tokenUsage: {
        input: 9_200,
        output: 3_100,
        cached: 3_400,
        contextUsed: 27_400,
        contextLimit: 128_000,
      },
      costUsd: 0.1,
      toolCalls: 5,
    },
    {
      id: "agent-agy-ux",
      parentId: "agent-claude-root",
      name: "Topology designer",
      provider: "agy",
      model: "agy-core",
      effort: "high",
      status: "running",
      task: "Design the cross-provider topology view",
      spawnMethod: "api",
      cwd: "~/projects/monitor-agents/design",
      startedAt: "2026-07-11T01:15:00.000Z",
      endedAt: null,
      lastActivityAt: "2026-07-11T04:54:00.000Z",
      tokenUsage: {
        input: 6_800,
        output: 2_200,
        cached: 1_100,
        contextUsed: 18_600,
        contextLimit: 64_000,
      },
      costUsd: 0.08,
      toolCalls: 4,
    },
    {
      id: "agent-codex-schema",
      parentId: "agent-codex-api",
      name: "Schema builder",
      provider: "codex",
      model: "codex-1",
      effort: "low",
      status: "completed",
      task: "Implement the telemetry domain types",
      spawnMethod: "native",
      cwd: "~/projects/monitor-agents/lib",
      startedAt: "2026-07-11T01:25:00.000Z",
      endedAt: "2026-07-11T01:50:00.000Z",
      lastActivityAt: "2026-07-11T01:50:00.000Z",
      tokenUsage: {
        input: 5_400,
        output: 1_800,
        cached: 2_100,
        contextUsed: 16_200,
        contextLimit: 128_000,
      },
      costUsd: 0.05,
      toolCalls: 3,
    },
    {
      id: "agent-claude-tests",
      parentId: "agent-codex-api",
      name: "Contract tester",
      provider: "claude",
      model: "claude-sonnet",
      effort: "medium",
      status: "completed",
      task: "Verify event and quota calculations",
      spawnMethod: "bash",
      spawnCommand: "claude -p \"verify telemetry calculations\"",
      cwd: "~/projects/monitor-agents/lib",
      startedAt: "2026-07-11T01:30:00.000Z",
      endedAt: "2026-07-11T02:00:00.000Z",
      lastActivityAt: "2026-07-11T02:00:00.000Z",
      tokenUsage: {
        input: 4_100,
        output: 1_500,
        cached: 900,
        contextUsed: 12_700,
        contextLimit: 200_000,
      },
      costUsd: 0.06,
      toolCalls: 2,
    },
    {
      id: "agent-codex-ui",
      parentId: "agent-agy-ux",
      name: "Dashboard builder",
      provider: "codex",
      model: "codex-1",
      effort: "high",
      status: "running",
      task: "Build the dashboard presentation layer",
      spawnMethod: "api",
      cwd: "~/projects/monitor-agents/components",
      startedAt: "2026-07-11T01:45:00.000Z",
      endedAt: null,
      lastActivityAt: "2026-07-11T04:56:00.000Z",
      tokenUsage: {
        input: 3_000,
        output: 900,
        cached: 800,
        contextUsed: 9_800,
        contextLimit: 128_000,
      },
      costUsd: 0.03,
      toolCalls: 2,
    },
    {
      id: "agent-agy-cost",
      parentId: "agent-codex-schema",
      name: "Cost verifier",
      provider: "agy",
      model: "agy-core",
      effort: null,
      status: "failed",
      task: "Reconcile provider pricing samples",
      spawnMethod: "api",
      cwd: "~/projects/monitor-agents/lib",
      startedAt: "2026-07-11T01:35:00.000Z",
      endedAt: "2026-07-11T01:42:00.000Z",
      lastActivityAt: "2026-07-11T01:42:00.000Z",
      tokenUsage: {
        input: 1_200,
        output: 400,
        cached: 200,
        contextUsed: 4_100,
        contextLimit: 64_000,
      },
      costUsd: 0.02,
      toolCalls: 1,
    },
  ],
  events: [
    {
      id: "event-tool-root",
      agentId: "agent-claude-root",
      kind: "tool.called",
      at: "2026-07-11T04:59:00.000Z",
      label: "Checked the delivery plan and active branches",
    },
    {
      id: "event-ui-started",
      agentId: "agent-codex-ui",
      kind: "agent.started",
      at: "2026-07-11T01:45:00.000Z",
      label: "Spawned by AGY through the agent API",
    },
    {
      id: "event-cost-failed",
      agentId: "agent-agy-cost",
      kind: "agent.failed",
      at: "2026-07-11T01:42:00.000Z",
      label: "Provider pricing sample did not match the recorded rate",
    },
    {
      id: "event-schema-completed",
      agentId: "agent-codex-schema",
      kind: "agent.completed",
      at: "2026-07-11T01:50:00.000Z",
      label: "Telemetry schema and derivation helpers completed",
    },
    {
      id: "event-usage-root",
      agentId: "agent-claude-root",
      kind: "usage.recorded",
      at: "2026-07-11T04:58:00.000Z",
      label: "Claude coordinator usage",
      inputTokens: 18_000,
      outputTokens: 4_600,
      costUsd: 0.21,
    },
    {
      id: "event-usage-api",
      agentId: "agent-codex-api",
      kind: "usage.recorded",
      at: "2026-07-11T02:20:00.000Z",
      label: "Codex API investigation usage",
      inputTokens: 9_200,
      outputTokens: 3_100,
      costUsd: 0.1,
    },
    {
      id: "event-usage-ux",
      agentId: "agent-agy-ux",
      kind: "usage.recorded",
      at: "2026-07-11T04:54:00.000Z",
      label: "AGY topology design usage",
      inputTokens: 6_800,
      outputTokens: 2_200,
      costUsd: 0.08,
    },
    {
      id: "event-usage-schema",
      agentId: "agent-codex-schema",
      kind: "usage.recorded",
      at: "2026-07-11T01:50:00.000Z",
      label: "Codex schema implementation usage",
      inputTokens: 5_400,
      outputTokens: 1_800,
      costUsd: 0.05,
    },
    {
      id: "event-usage-tests",
      agentId: "agent-claude-tests",
      kind: "usage.recorded",
      at: "2026-07-11T02:00:00.000Z",
      label: "Claude contract test usage",
      inputTokens: 4_100,
      outputTokens: 1_500,
      costUsd: 0.06,
    },
    {
      id: "event-usage-ui",
      agentId: "agent-codex-ui",
      kind: "usage.recorded",
      at: "2026-07-11T04:56:00.000Z",
      label: "Codex dashboard usage",
      inputTokens: 3_000,
      outputTokens: 900,
      costUsd: 0.03,
    },
    {
      id: "event-usage-cost",
      agentId: "agent-agy-cost",
      kind: "usage.recorded",
      at: "2026-07-11T01:42:00.000Z",
      label: "AGY cost verification usage",
      inputTokens: 1_200,
      outputTokens: 400,
      costUsd: 0.02,
    },
  ],
  quotaLimits: [
    {
      id: "quota-codex-five-hour",
      provider: "codex",
      label: "Codex 5-hour window",
      period: "hour",
      windowHours: 5,
      usedTokens: 23_400,
      tokenLimit: 100_000,
      usedCostUsd: 0.18,
      costLimitUsd: 2,
      usedPercent: 23.4,
      resetsAt: "2026-07-11T06:00:00.000Z",
    },
    {
      id: "quota-claude-week",
      provider: "claude",
      label: "Claude weekly window",
      period: "week",
      windowHours: 168,
      usedTokens: 28_200,
      tokenLimit: 500_000,
      usedCostUsd: 0.27,
      costLimitUsd: 10,
      usedPercent: 5.64,
      resetsAt: "2026-07-14T00:00:00.000Z",
    },
    {
      id: "quota-agy-week",
      provider: "agy",
      label: "AGY weekly window",
      period: "week",
      windowHours: 168,
      usedTokens: 10_600,
      tokenLimit: 250_000,
      usedCostUsd: 0.1,
      costLimitUsd: 5,
      usedPercent: 4.24,
      resetsAt: "2026-07-14T00:00:00.000Z",
    },
  ],
  sources: [
    {
      provider: "codex",
      connection: "connected",
      detail: "Demo source",
      agentCount: 3,
    },
    {
      provider: "claude",
      connection: "connected",
      detail: "Demo source",
      agentCount: 2,
    },
    {
      provider: "agy",
      connection: "connected",
      detail: "Demo source",
      agentCount: 2,
    },
  ],
};
